//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBook.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootballPlayerPosition
    {
        public int Id { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PerformansRate { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
