//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatistic
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> TypeOfLeagueId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PlayedGameCount { get; set; }
        public Nullable<int> WinCount { get; set; }
        public Nullable<int> DrawCount { get; set; }
        public Nullable<int> LostCount { get; set; }
        public Nullable<int> GoalCount { get; set; }
        public Nullable<int> AssistCount { get; set; }
        public Nullable<int> TotalMinute { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
