//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
        public string ColorOfJersey { get; set; }
        public string JerseyUrl { get; set; }
        public Nullable<int> StadiumId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
